### ISSUE TITLE
samba:smbd-only-latest remains unhealty, everything works though

### ISSUE THREAD

**Issue by maikvitesse** [ServerContainers/samba#101]
Recently switched from :latest to :smbd-only-latest because i don't use avahi and wsdd2.
The health check from :latest is working fine, but the health check from :smbd-only-latest remains unhealthy.

Don't know for sure if it's something with the build or my configuration.

Unhealthy status in Portainer:
![1](https://github.com/ServerContainers/samba/assets/4076676/72c29ce0-911b-4e22-b294-73e2c67a66d2)

Log from Portainer:
![2](https://github.com/ServerContainers/samba/assets/4076676/145f3aa6-521a-4654-ba70-bf9984a4234f)

Configuration:
![3](https://github.com/ServerContainers/samba/assets/4076676/84e7e36f-bf5c-4c42-8c1e-51807d72f632)

**Comment by MarvAmBass** [comment]
thanks for the issue, I thought I fixed it.

**Comment by maikvitesse** [comment]
no problem! then at least it's not just me 😄

**Comment by MarvAmBass** [comment]
can you try to explicitly disable the not available services using ENVS:

```
AVAHI_DISABLE: disabled
WSDD2_DISABLE: disabled
```

My healthcheck should notice that those are not enabled and should work - I made them into the reduced build, but maybe they are not working somehow...

**Comment by MarvAmBass** [comment]
I've fixed some string, which might be problematic, and testet the local build locally - it works now on my machine
