### ISSUE TITLE
Remove network_mode: host from docker-compose.yml

### ISSUE THREAD

**Issue by clach04** [ServerContainers/samba#103]
Provided docker-compose.yml states using network_mode=host isn't a good idea/recommended... then uses network_mode=host :laughing: 
https://github.com/ServerContainers/samba/blob/15ff1626b7bf14653917556f48c2f1edb3fcc582/docker-compose.yml#L10

Extract with more context:

    # note that this network_mode makes it super easy (especially for zeroconf) but is not as safe as exposing ports directly
    # more about that here: https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-security/docker-breakout-privilege-escalation#hostnetwork
    network_mode: host

Should this be the default?

**Comment by MarvAmBass** [comment]
If you think samba/fileserver/timemachine backup system and docker you need to free yourself from the normal container behavior.

in case of this container it is meant to be used as an easy way to free yourself from whatever samba packaging your distributor does. and gives you a sane, "battle tested" easy to use samba configuration for everything your NAS or Storage System needs.

if you don't already know about the implications about `network_mode` (I also added a warning to make people aware that they should read about the consequences) then it's just a hussle if stuff doesn't work as expected.
you for example missed the zeroconf ports, which are random - can't really expose them, and it doesn't work over routed networks.

also, it's very likely that all the important files are already mounted into the container (samba fileserver) - there is no real need to escalate somewhere else, you finished you're goal once you gained access to the container

if you take all this considerations into account, and which such a big userbase there might be many people who want a solution which just works it's fine and not a big risk
