### ISSUE TITLE
Image builds broken

### ISSUE THREAD

**Issue by jnoordsij** [ServerContainers/samba#106]
The automatic image builds seem broken due to 9ac7f29f5ff13abaa668777812ed8c72135378ca, which runs the `build.sh` script to detect wether or not a new version is needed, but now always fails with message `error please specify docker-registry DOCKER_REGISTRY`.

I noticed this since [Alpine 3.18.4 has been released](https://www.alpinelinux.org/posts/Alpine-3.18.4-released.html), but no image has appeared as of yet.

See for example https://github.com/ServerContainers/samba/actions/runs/6399103067/job/17370544350#step:7:12

**Comment by MarvAmBass** [comment]
Thanks for noticing, I'll look into it tomorrow 👍

**Comment by MarvAmBass** [comment]
Fixed 👍 will now use correct registry to check wether image is already build or not

**Comment by jnoordsij** [comment]
Thanks a lot for the quick fix!
