### ISSUE TITLE
users group always with the id 100 whatever 

### ISSUE THREAD

**Issue by StSixtus** [ServerContainers/samba#108]
The id of the group "users" is 100, whatever value I put in the env
In the docker-compose.yml there is
      environment:
         - GROUP_users=1011

But in the samba container the /etc/group contains
users:x:100:games,z210
The z210 was a value I put in the env. But the 100 isn't the value, I put in env.
By the way, I wonder why the user games is here ?

I had to manually set this id to the one expected in order to write to the share.

I'm using the latest version on arm64, and deleted the container and its image in order to force the generation of conf files like smb.conf.
When I inspect the image I get
servercontainers/samba@sha256:a10c857fa6100a6cb2ab60f1eed81ab5f93ca0b259f8aa8ad89be57fa2af34fb

**Comment by MarvAmBass** [comment]
you're using a groupname which is already used as a system group `users` - just use a different group name and it should be fine - for example use `Users` as groupname

if you really want to chance the id of the system group you can alter /etc/group in your own image which might be based on my image

list of groups you can't use `docker run -ti --rm alpine cat /etc/group`

```
root
bin
daemon
sys
adm
tty
disk
lp
mem
kmem
wheel
floppy
mail
news
uucp
man
cron
console
audio
cdrom
dialout
ftp
sshd
input
at
tape
video
netdev
readproc
squid
xfs
kvm
games
shadow
cdrw
www-data
usb
vpopmail
users
ntp
nofiles
smmsp
locate
abuild
utmp
ping
nogroup
nobody
```

**Comment by StSixtus** [comment]
Thanks for your quick and complete response.
I changed the group name and it worked immediately.

This image is quite convenient.
