### ISSUE TITLE
Question: Which version of Samba (v1/v2/v3/v4) is being used, and can it be changed for best performance? 

### ISSUE THREAD

**Issue by mr-honest** [ServerContainers/samba#114]
Hi, 
Just want to tell you thank you for the image. I was not able to get samba working in Debian 12 native, probably to some security settings, I could not figure out. 
This image works just fine, and I have set it up to my liking.

One thing I am in doubt about. Which SMB version is being used by your image, and can I change it by a environment variable if needed?
I could not detect anything in the docker-compose file.  
I want maximum throughput over my samba, and want to use optimal version.

My setup:
SAMBA server is on Debian 12 host, x86, intel n100 processor, 1gbit
SAMBA client is Windows 11 machine, 1gbit.  

I dont need backward compatibility etc etc.. Just maximum performance.

**Comment by MarvAmBass** [comment]
Hi there,

to choose versions you can use the container tags, a... is alpine version, s... is samba version

https://github.com/ServerContainers/samba/pkgs/container/samba/versions?filters%5Bversion_type%5D=tagged

keep in mind, that older container versions might have some bugs, or nmbd missing - you can check the changelog and dates for the bugfixes and changes

also note, that not all versions are available - there might be a view on the old docker hub version as well

but I would not recommend to use an older samba version, maybe stick to 1-3 versions earlier if you experience a bug - but try to update as soon as it's working

that's also the great thing about containers, just use a different tag and run your config on another samba version - so you can test if the latest version is working, if not revert back and open an issue here :)

if you need performance, don't mount multiple shares into one another, this make everything super slow -> I stumpled across this issue :D

**Comment by mr-honest** [comment]
![image](https://github.com/ServerContainers/samba/assets/2685211/f0c145c3-6bd6-4535-bbbb-6ccdfaa79d26)
Perfect: 
I am using this image:  ghcr.io/servercontainers/samba:smbd-only-latest
Just figured out it was 2 month old, and not 10 days old :)
When I log into the container 
![image](https://github.com/ServerContainers/samba/assets/2685211/f5f93f45-88fb-44d1-b437-6bf5a149a0a6)
I see the samba version is 4.18.5 and I use SMBv3_11 in the connection. 

So eventhough samba is 4.18.5, I still use SMBv3 in the connection to the PC. Is there any upside to using SMBv4?

**Comment by mr-honest** [comment]
One last question, 

I do not understand the need for the line in the docker-compose, and never used it before. I dont see any differences commenting  it out.

    **build: .**

What does it do, and should I leave it enabled?

**Comment by MarvAmBass** [comment]
you can remove it, its for people who checkout the repo and build the container themself
I'd recommend this actually, you never know what other buildservers inject

please checkout some introductional video on docker and docker compose - I guess there are many on youtube which will help you understand how to use and work with containers - it's worth it :)

**Comment by MarvAmBass** [comment]
regarding the other questions, you can overwrite every samba setting - but keep in mind this is a container for a broad audience - it's made to be stable and work long term - even if it might not use the latest features etc.

it's there to give users an easy way to specifiy shares, grouping, users and even timemachine backup support

if you want to support a very specific scenario it makes sense to build your own container with exactly the setup you need.
you might need to read a lot of samba documentation to see the pros and cons of the settings etc.
