### ISSUE TITLE
Why does turning on time machine modify my read and write permissions

### ISSUE THREAD

**Issue by reqyo** [ServerContainers/samba#116]
Running this for my time machine back up and one as a general drive. Both on seperate mount points.

`docker run -d \
  --name samba \
  --net=host \
  -e MODEL=MacPro7,1@ECOLOR=226,226,224 \
  -e SAMBA_CONF_GLOBAL="server string = My Samba Server" \
  -e SAMBA_VOLUME_CONFIG_SPACEDRIVE="[SpaceDrive]; path=/share/spacedrive; guest ok = yes; browseable = yes; read only = no;" \
  -e SAMBA_VOLUME_CONFIG_TIMECAPSULE="[TimeCapsule]; path=/share/timecapsule; fruit:time machine = yes; guest ok = yes; browseable = yes; read only = no;" \
  -v /mnt/timecapsule:/share/timecapsule \
  -v /mnt/spacedrive:/share/spacedrive \
  -v /etc/avahi/services:/external/avahi \
  ghcr.io/servercontainers/samba`
  
  When turning on time machine for my time capsule share, it changes the permissions of my mount point from
  
  `drwxrwxrwx 3 root root 4096 Dec 29 01:04 timecapsule/`
  to 
  `drwx------ 3 root root 4096 Dec 29 01:04 timecapsule/`
  
  Is this expected behaviour? But I cannot use it to backup on my mac after the fact with this strict level of access.

**Comment by MarvAmBass** [comment]
Hi there,

you're right - I've implemented this as a fix a long time ago.
https://github.com/ServerContainers/samba/blob/master/scripts/entrypoint.sh#L202

So you want timemachine to backup as a guest - am I right?

A possible quick fix would be to force the user/group on this share to root - so it has normal write access

```
force group = root;force user = root
```

Other than that - I'm not sure if I can safely remove my added fix - can't remember why I added it years ago - but I don't want to risk breaking this functionallity for many users

it seems you're the first one who gives timemachine access for guests 😄 

you could also add a user using envs and add this user `bob` to the valid users e.g.: `valid users = alice;`

```
      ACCOUNT_bob: bobpass
```

**Comment by reqyo** [comment]
Hey Marv, thanks! Yeah tbh I'm the only one on my network that uses the mac and the backup is encrypted anyways (so I don't think the whole guest thing will affect me too much)! Thanks for the reply dude I will try that today, and of course, let's not break it for everyone! :D If it doesn't work I will just add a user to that particular share.

**Comment by reqyo** [comment]
Yep Marv, that worked perfectly! Thanks so much. 

I wanted to ask another 2 questions, apologies for the hand holding here, but in terms of adding say a user for the timecapsule share, is it a matter of just creating a user and password and assigning it to the share? 

```
docker run -d \
  --name samba \
  --net=host \
  -e MODEL=MacPro7,1@ECOLOR=226,226,224 \
  -e SAMBA_CONF_GLOBAL="server string = My Samba Server" \
  -e SAMBA_VOLUME_CONFIG_SPACEDRIVE="[SpaceDrive]; path=/share/spacedrive; guest ok = yes; browseable = yes; read only = no;" \
  -e SAMBA_VOLUME_CONFIG_TIMECAPSULE="[TimeCapsule]; path=/share/timecapsule; fruit:time machine = yes; valid users = bob; guest ok = no; browseable = yes; read only = no;" \
  -e ACCOUNT_bob = "password" \
  -v /mnt/timecapsule:/share/timecapsule \
  -v /mnt/spacedrive:/share/spacedrive \
  -v /etc/avahi/services:/external/avahi \
  ghcr.io/servercontainers/samba

```

And one small but annoying thing (its macOS fault I believe) on Sonoma, why when you backup do you not get the cool little green icon anymore? Is it the same for you if you use time machine at all? No worries if not mate :) just my OCD kicking in. I think it most likely still works for connected drives

![Screenshot 2023-12-29 at 10 04 59](https://github.com/ServerContainers/samba/assets/19641573/e62d8184-4ec4-4ae6-9635-b78be6968ba3)

**Comment by MarvAmBass** [comment]
thanks, I'm glad I could help - so it works even with guest user and no password right now?

yeah, adding a user is really just adding a `ACCOUNT_$username="password"` environment variable - it's also possible to not use a plaintext password - and to use a hash instead - maybe you don't want to know all passwords of colleagues or family members -> see readme on how this is done

I also added functionallity to specify the UID for and account using `UID_$username=1000`

and grouping is also done so you can have shares where everyone can write, or some can write and others only read etc.

<img width="40" alt="Screenshot 2023-12-29 at 22 08 10" src="https://github.com/ServerContainers/samba/assets/8941027/5f4c675a-35a0-4da9-9e94-18d4cb4ef279">

good question about the green icon - I've disabled those on the desktop and I only have the timemachine backup symbol in the macos top bar near the clock.
but I'm pretty sure this is a general change in the macos

have fun using my container!
