### ISSUE TITLE
`disable netbios = yes` disregards `$NETBIOS_DISABLE`

### ISSUE THREAD

**Issue by igorbernstein** [ServerContainers/samba#118]
https://github.com/ServerContainers/samba/blob/83a6064602838b29493063cd627b95a9af1e8f91/scripts/entrypoint.sh#L72-L76

I think there is a logic error here, shouldn't `echo '   disable netbios = yes' >> /etc/samba/smb.conf ` be inside the `if` body?

**Comment by MarvAmBass** [comment]
haha hi there, thanks for noticing - don't know how I missed this - should be fixed now :)
