### ISSUE TITLE
enable encryption

### ISSUE THREAD

**Issue by milsanore** [ServerContainers/samba#128]
Hi, some online [reading](https://www.makeuseof.com/ways-to-secure-samba-server-on-linux) suggests that SMB traffic should be encrypted.
Two questions:

1) Is this a good idea?
2) If so, how?

[SO](https://serverfault.com/a/1088412) suggests something like this:
```
[global]
   # smb v4.14 and later
   server signing = mandatory
   server min protocol = SMB3
   server smb encrypt = required
   # smb v4.13 or earlier
   smb encrypt = required
```

Below is the content of `/etc/samba/smb.conf` in my samba container.
I guess I could mount /etc/samba as volume and then edit the content.
Is this the recommended approach?
Thank you for this container btw.

```
[global]
   server role = standalone server
   log file = /dev/stdout
   dns proxy = no 

   # password stuff
   passdb backend = smbpasswd

   obey pam restrictions = yes
   security = user
   printcap name = /dev/null
   load printers = no
   dns proxy = no
   wide links = yes
   follow symlinks = yes
   unix extensions = no
   acl allow execute always = yes

   # MacOS Compatibility options
   vfs objects = catia fruit streams_xattr

   # Special configuration for Apple's Time Machine
   fruit:model = TimeCapsule
   fruit:aapl = yes

   # Docker Envs global config options
   log level = 1
   workgroup = WORKGROUP
   server string = Samba Server
   map to guest = Bad User

[share]
 path=/shares/share
 ...
```

**Comment by MarvAmBass** [comment]
Take a look at the readme, there you'll see how to set global options

<img width="771" alt="Screenshot 2024-05-06 at 13 09 30" src="https://github.com/ServerContainers/samba/assets/8941027/a53fa82a-3505-43b1-8aec-afeada0ba845">

**Comment by milsanore** [comment]
thank you!
