### ISSUE TITLE
Scheduled Docker builds failing

### ISSUE THREAD

**Issue by jnoordsij** [ServerContainers/samba#130]
Alpine 3.20 was [released yesterday](https://alpinelinux.org/posts/Alpine-3.20.0-released.html), but I noticed no new image being available yet. A quick peak into recent action logs showed that [scheduled builds are failing](https://github.com/ServerContainers/samba/actions/runs/9199236156) with the following error:
```
buildx failed with: ERROR: failed to solve: failed to push 4.19.6-r0: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Alibrary%2F4.19.6-r0%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized
```

It looks to me that this is either some secret misconfiguration that requires attention, or else possibly (indirectly) caused by the reported deprecated actions.

**Comment by MarvAmBass** [comment]
fixed - there was a regex problem which resulted in breaking the docker tag

**Comment by jnoordsij** [comment]
Great, thanks for your very quick action!
