### ISSUE TITLE
Raspberry Pi setup using the default pi user

### ISSUE THREAD

**Issue by bradenmitchell** [ServerContainers/samba#136]
I'm just starting to play around with setting up samba myself (having previously relied on OpenMediaVault) on a raspberry pi acting as a NAS. I am having issues accessing the volumes on my Mac.

I have a `pi` user setup and I remote in as `pi@raspberrypi.local`. If I setup a volume as follows, when I try to access it as a 'Registered User' from my Mac using the `pi` username and password, it denies access.

```
services:
  samba:
    image: ghcr.io/servercontainers/samba
    restart: always
    network_mode: host
    environment:
      SAMBA_VOLUME_CONFIG_pitest: |
        [Pi Test Share]
          path = /shares/pi-test
          valid users = pi
          guest ok = no
          read only = no
          browsable = yes
    volumes:
      - /mnt/pi-test:/shares/pi-test
```
    

Does this container require users to be added explicitly as in the example `docker-compose.yml`? Or can it reuse user accounts already on the device (as in the default `pi` user)?

**Comment by MarvAmBass** [comment]
a container doesn't know the users of it's host - it's not that far away from a virtual machine - for example, with the `networks_mode: host` you explicitly tell docker to not give this container it's own network - this is needed for avahi.

just add users and groups as you like using the environment variables - take a look at the readme and `docker-compose.yml` I provided
