### ISSUE TITLE
Cannot add or use user with UID 33

### ISSUE THREAD

**Issue by goofacz** [ServerContainers/samba#138]
I've problem with using or adding user with UID 33. Some time ago base image (alpine) had user `xfs` with that UID but apparently it's not true any more:
```
[me@host samba]$ docker exec --user root -it samba-samba-1 sh       
/ # id xfs
id: unknown user xfs
```

The `/etc/passwd` doesn't have any user with UID 33. Moreover, listing directory with host's volumes proves there's no user with UID 33 in the container:
```
/ # ls -l /shares/
total 0
drwxr-xr-x    1 33       http           140 Dec 20  2023 storage
```

I tried adding user at runtime:
```
/ # adduser -u 33 -g 33 xhttp
```
or via CFG via cfg:
```
ACCOUNT_xhttp: qwerty
USER_xhttp: 33
```
Both method end up with `adduser: uid '33' in use`

I need user with UID 33 because it's used on my host system and I have to pass it to Samba's `force user` to assure correct R/W access.

Do you have any idea how to deal with that?

**Comment by MarvAmBass** [comment]
it works on alpine, I've tried in my container and got:

```
/ # cat /etc/passwd | grep 33
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
/ # id xfs
uid=33(xfs) gid=33(xfs) groups=33(xfs),33(xfs)
```

it seems to be added by one of the dependencies of this container.
why don't just use force user to xfs, than it uses id `33` - you can also use `force group xfs` and it should work

**Comment by goofacz** [comment]
The thing is I don't have `xfs` user in the `samba` container and I cannot add it because UID 33 is occupied. I used `force user = xfs` in the past. It broke recently. I'll continue the investigation.

@MarvAmBass You `grep`ed `passwd` on vanilla Alpine or samba image?

**Comment by MarvAmBass** [comment]
what user does uid 33 occupy? just use the user which holds uid 33 and you're fine.
you could also create your own docker container which is based on mine and hack your user into it

**Comment by WargAlta** [comment]
@goofacz I had the same issue, I couldn't access my Nextcloud folders as they need group 33 (www-data in Ubuntu, xfs in Alpine). 
I found that the Alpine Team did some cleanup on their distro, starting 3.20:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/15453
They removed several old groups, including xfs (gid 33).

To resolve the issue, I created a simple Dockerfile in my ./samba/ directory:
```
FROM ghcr.io/servercontainers/samba:latest

# Add back group and user 33 for xfs
RUN addgroup -g 33 -S xfs && \
    adduser -u 33 -D -S -G xfs xfs
```

Then in my docker-compose file, I replaced `image: ghcr.io/servercontainers/samba:latest` with build: ./samba

I launched my container with docker-compose **up --build -d** and my shares are back online for write and read, without changing anythinf else.

Thanks @MarvAmBass for keeping up this project !

**Comment by WargAlta** [comment]
Unfortunately, not on my end.
I tried and ran into the same issue described in the initial request:
```
ACCOUNT: adding account: alice with UID: 33
adduser: uid '33' in use
```
The `cat /etc/passwd | grep 33` command return nothing.

When I use the Dockerfile, the command returns:
```
/ # cat /etc/passwd | grep 33
xfs:x:33:33:Linux User,,,:/home/xfs:/sbin/nologin
```
and my access works as expected.

**Comment by goofacz** [comment]
@MarvAmBass Yup, I ended up with the same solution.
@WargAlta I tried that, it didn't work for me.
