### ISSUE TITLE
Fail early on failed user creation

### ISSUE THREAD

**Issue by empwilli** [ServerContainers/samba#139]
I think it would be useful if the startup script would stop/fail early, if there was an error in the user creation. Currently, these errors are reported to the container logs but the server starts up anyway. 

In my setup I had a faulty group ID and I struggled for quite some time why I couldn't connect to the server. IMHO this qualifies as an unrecoverable configuration error and the startup script should fail.

I'm looking for thoughts/opinions and if you want to I can take care of this issue.

**Comment by MarvAmBass** [comment]
thanks for the request, you mean if you have a uid / gid collision? or do you have other problems in mind?

**Comment by empwilli** [comment]
In this case I had a GID collision with an additional group.

**Comment by h-arnold** [comment]
Hey all! 

I had the same issue and while I haven't adjusted the script to fail early, I think I've fixed the big you're referring to here: https://github.com/ServerContainers/samba/pull/140

I've added logic to the entrypoint.sh script to check for existing users and delete them if they exist and moved the group creation to follow the user creation to avoid GID collisions.

**Comment by MarvAmBass** [comment]
`IMHO this qualifies as an unrecoverable configuration error and the startup script should fail.` depends on the point of view, if a medium sized company uses the container - why should the fileserver be dead just because one or two users are configured not properly.

**Comment by MarvAmBass** [comment]
added env variable to trigger fail fast mode
