### ISSUE TITLE
Multiple account problem

### ISSUE THREAD

**Issue by think-free** [ServerContainers/samba#35]
Using the latest image from docker hub :

When defining several account in docker-compose file the entrypoint script seems to take all defined users as one multiline user :

docker-compose.yml (partial content)
    environment:
      ACCOUNT_aaa: aaapass
      ACCOUNT_bbb: bbbpass

>> ACCOUNT: adding account: aaa
samba    | bbb
samba    | useradd: invalid user name 'aaa
samba    | bbb'
samba    | passwd: user 'aaa
samba    | bbb' does not exist

**Comment by MarvAmBass** [comment]
hi, thanks for finding this bug - I'll see how I can fix this

**Comment by think-free** [comment]
Just to clarify that just cloning the git repo you can reproduce the bug using the provided compose file

**Comment by think-free** [comment]
If you change the lines 96 to 108 of the entry point by the while loop in the file attached, it should solve the problem
[test.txt](https://github.com/ServerContainers/samba/files/2783374/test.txt)

**Comment by think-free** [comment]
Sorry, I've tested it on ubuntu ...
The fix was working in bash, not sh, it's not working

/usr/local/bin/entrypoint.sh: 107: /usr/local/bin/entrypoint.sh: Syntax error: redirection unexpected

**Comment by think-free** [comment]
echo "$(env | grep '^ACCOUNT_')" | while IFS= read -r I_ACCOUNT ; do

Work with sh on ubuntu,

**Comment by think-free** [comment]
[That](https://github.com/ServerContainers/samba/files/2783850/entrypoint.sh.txt) worked.
I've build the docker image and tested it

samba_1  | >> CONTAINER: starting initialisation
samba_1  | >> SAMBA CONFIG: no $SAMBA_CONF_WORKGROUP set, using 'WORKGROUP'
samba_1  | >> SAMBA CONFIG: no $SAMBA_CONF_SERVER_STRING set, using 'file server'
samba_1  | >> SAMBA CONFIG: no $SAMBA_CONF_MAP_TO_GUEST set, using 'Bad User'
samba_1  | >> SAMBA CONFIG: enabling Apple's SMB2+ extentions
samba_1  | >> ACCOUNT: adding account: bob
samba_1  | Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
samba_1  | New SMB password:
samba_1  | Retype new SMB password:
samba_1  | Added user bob.
samba_1  | Enabled user bob.
samba_1  | >> ACCOUNT: adding account: alice
samba_1  | Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
samba_1  | New SMB password:
samba_1  | Retype new SMB password:
samba_1  | Added user alice.
samba_1  | Enabled user alice.
samba_1  | >> CMD: exec docker CMD
samba_1  | bash -c smbd -FS -d 2 < /dev/null

**Comment by MarvAmBass** [comment]
wow thanks so much for figuring it out

I just updated it, let's hope it works well

**Comment by think-free** [comment]
You are welcome, thank you for the project ;)
It's working fine now, closing the ticket.
Thanks
