### ISSUE TITLE
Adding users to groups

### ISSUE THREAD

**Issue by ranseyer** [ServerContainers/samba#38]
Hi,

i think i need my samba users in a group. So i have changed the start command. This is not really good readable. 

So the questions: 
- do i havent seen an beeter way ?
- or is it possible the extend the next image with an better solution ?

Here my start-command:
`    command: /bin/bash -c "usermod -aG users user1&usermod -aG users user2&usermod -aG users user3&usermod -aG users user4&usermod -aG users user5&smbd -FS -d 2 < /dev/null"

`

Greetings
![bitmoji](https://render.bitstrips.com/v2/cpanel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-7b1feebf-d814-41d6-97bb-9cd62b0d58b0-v1.png?transparent=1&palette=1&width=246)

**Comment by MarvAmBass** [comment]
Good question, adding this funcitonality will either add some strange looking envs or break compatibility.

if you solution works for you, why not - and If you want a cleaner solution you can fork my project and alter the user creation part

**Comment by ranseyer** [comment]
Thank, you !
then i will use it in my little bit strange way.

(thought others will have the same problem...)
