### ISSUE TITLE
Over verbose logging to stdout (and thus into the Docker Host's syslog.)

### ISSUE THREAD

**Issue by barberio** [ServerContainers/samba#42]
Samba seems to be configured to provide a very verbose logging output to stdout, including registering every time a file is opened and closed. When being used for a Time Machine backup, this is a *lot* of spam into syslog on the Docker Host.

It does not appear possible to configure this through setting SAMBA_GLOBAL_CONFIG_log or SAMBA_GLOBAL_CONFIG_log_level.

Workaround is to set the docker instance's logging driver to 'none', but of course this entirely disables logging for it.

Sample:
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6bb read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/663 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6af read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/34 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/69a read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/679 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6ab read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/69e (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/69d read=No write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/69d (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/69d read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/6b8 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6a9 read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/5b (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/696 read=No write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/696 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/696 read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/63 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6a0 read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/699 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/69e read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/69b (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/69b read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/6b4 (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6c9 read=Yes write=No (numopen=16)
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio closed file luxo.sparsebundle/bands/6af (numopen=15) NT_STATUS_OK
> Aug 07 20:46:09 wall-e docker-compose[929]: samba_1          | barberio opened file luxo.sparsebundle/bands/6bf read=Yes write=No (numopen=16)

**Comment by MarvAmBass** [comment]
Hi there,

thanks for your Issue - now that I read that - my samba container also spams it's logs.

I also found the solution to it and will provide a env variable where one can set the `log level` and make `1` the default

should be done in a few hours ;)

**Comment by MarvAmBass** [comment]
fixed and pushed ;)
