### ISSUE TITLE
[Question] Can't pass global environment variables

### ISSUE THREAD

**Issue by shadowking001** [ServerContainers/samba#43]
Hello,

I'm struggling to add a global variable to the smb.conf file through environment variables.
For some testing purpose, I'm trying to make sure devices still using SMBv1 can connect. So I'd like to set the "client max protocole" global directive to nt1 to ensure I can still join it.

Reading your readme, I thought that this would make the job :

```
...
environment:
   - SAMBA_GLOBAL_CONFIG_CLIENT_SPACE_MAX_SPACE_PROTOCOL=nt1
...
```

There's some evidence that I'm doing it the wrong way, this results in :

```
   # Docker Envs global config options
   log level = 1
   workgroup = WORKGROUP
   server string = Samba Server
   map to guest = Bad user
   nt1
```

Obviously, I'm not heading in the right direction, if you could give me any advice I'd be grateful.

**Comment by MarvAmBass** [comment]
Hi there, can you please provide me with the logs?

especially lines starting with: `>> global config - adding: `

did you pull the latest container version?

maybe it's a bug, but I'll take a closer look tomorrow - if it's a bug, should be fixed within the next 24h

**Comment by shadowking001** [comment]
```

>> CONTAINER: starting initialisation,
>> ACCOUNT: adding account: media with UID: 1035,
>> global config - adding: 'nt1' to /etc/samba/smb.conf,
>> SAMBA CONFIG: no $SAMBA_CONF_SERVER_STRING set, using 'Samba Server',
>> SAMBA CONFIG: no $SAMBA_CONF_WORKGROUP set, using 'WORKGROUP',
>> SAMBA CONFIG: no $SAMBA_CONF_LOG_LEVEL set, using '1'
```

Image was up-to-date

**Comment by MarvAmBass** [comment]
found the bug, I somehow forgot to add the key - of the key value pair - it's already building all container architectures and should be pushed and available in ~20 minutes

thanks for filing this bug 👍

**Comment by MarvAmBass** [comment]
it's already pushed and available - wow that was fast 😄

**Comment by shadowking001** [comment]
Works like a charm ! Ty !
