### ISSUE TITLE
Custom Docker setup

### ISSUE THREAD

**Issue by vdhub** [ServerContainers/samba#46]
Greetings, 

Is there a way to have a custom docker image or server setup in order to run a samba that supposed to serve files on MacOS and Windows and as well a mariadb server , both on the same image ? and just to configure image and run it once at startup on each Debian machine ? 

Thanks in advance

**Comment by shadowking001** [comment]
Docker logic is about isolating applications, not mixing them. You'd better run a database container from a single docker-compose file.

**Comment by vdhub** [comment]
hmm, so what would be the best way in deploying a setup like that , I was looking on this as docker setup and containers instead of installing all on the host as it is now. so by having a image with all the solution could be easy to deploy and setup devices. Maybe I'm getting this wrong in this case .

**Comment by MarvAmBass** [comment]
closed - not an issue.

why would you do that? What keeps you from installing samba and mariadb on the server?

Other than that. I'd create a docker-compose.yml for each service and start it. take a look at this: https://github.com/MarvAmBass/docker-zoneminder/blob/master/docker-compose.yml

here you'll find a `mariadb` container and a container for database backups. Also there is a db-client in this case it's zoneminder.
