### ISSUE TITLE
Hash passwords - Instructions unclear

### ISSUE THREAD

**Issue by a1ad** [ServerContainers/samba#52]
Sorry to bother you, but I can't get hash password to work. The creation of the hash is working fine and this is my config:
`
ACCOUNT_jeroen: jeroen:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:21611C6EKJHKJHKJHB56F8CB9E6:[U]:LCT-61B0641E
`
It's valid yml and docker is starting just fine, but I can't log in.

The explanation on github is not super clear.

**Comment by MarvAmBass** [comment]
hey there, no problem - maybe I'll add a example in the `docker-compose.yml`

try to change the line to

```
ACCOUNT_foo: "foo:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:86C156FC198B358CCCF6278D8BD49B6A:[U          ]:LCT-61B0859A:"
```
