### ISSUE TITLE
Helthcheck failed

### ISSUE THREAD

**Issue by firkeuf** [ServerContainers/samba#54]
The avahi-daemon runs as the avahi user.
The health check script first filters out processes with the root user `ps aux | grep '[0-9] root'`. 
This results in an unhealthy container status.

ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 runsvdir -P /container/config/runit
  101 root      0:00 runsv wsdd2
  102 root      0:00 runsv avahi
  103 root      0:00 runsv samba
  104 root      0:00 smbd --foreground
  105 root      0:00 /usr/sbin/wsdd2
  108 avahi     0:00 avahi-daemon: running [udocker.local]
  109 avahi     0:00 avahi-daemon: chroot helper
  111 root      0:00 {smbd-notifyd} smbd --foreground
  112 root      0:00 {cleanupd} smbd --foreground
  113 root      0:00 /usr/lib/samba/samba-bgqd --ready-signal-fd=45 --parent-watch-fd=12 --debuglevel=9 -F
  152 root      0:00 sh
  220 root      0:00 ps aux

**Comment by MarvAmBass** [comment]
thanks for the bug report -> should be a easy fix -> I'll start working on it and close is as soon as the fix is pushed ;)

**Comment by MarvAmBass** [comment]
fix applied... container build running...
