### ISSUE TITLE
Deleted files seems to be moved back automatically in 4.15.2-rc0

### ISSUE THREAD

**Issue by cheneyveron** [ServerContainers/samba#56]
## Problem Description

After updating to Samba 4.15.2-rc0, files deleted through smb client are automatically added back.

## Things I've done to verify

1. There's no log about it. Even after set log level to 10.
2. I tried turn off/off recycle plugin and it doesn't help.
3. When I roll back to samba 4.14.8, everything is fine.

## Detailed conf

Here's my env confs:

| Environment Variable | Value |
|------------------------|------|
| SAMBA_GLOBAL_CONFIG_server_SPACE_min_SPACE_protocol | NT1 |
| SAMBA_GLOBAL_CONFIG_ntlm_SPACE_auth | ntlmv1-permitted |
| SAMBA_GLOBAL_CONFIG_bind_SPACE_interfaces_SPACE_only | Yes |
| SAMBA_CONF_LOG_LEVEL | 10 |
| SAMBA_VOLUME_CONFIG_public | [public] ; ea support = No ; kernel share modes = No ; mangled names = no ; nt acl support = No ; path = /mnt/public ; posix locking = No ; read only = No ; vfs objects = catia fruit streams_xattr crossrename recycle ; fruit:resource = stream ; fruit:metadata = stream ; fruit:encoding = native ; crossrename:sizelimit = 5000 ; nfs4:chown = true |

**Comment by MarvAmBass** [comment]
Hi there,

thanks for your issue - sounds like a super strange issue - I'll look into it but might need a few days

I'll keep you updated

**Comment by MarvAmBass** [comment]
@cheneyveron hi there, I was able to recreate this issue - super strange, I'd bet it either is a broken package build in alpine system / package. or samba itself has a problem.

if you find a solution, let me know and I try to fix this container - other than that I guess we have to wait for a new version with a fix.

great to know that the version/docker tag `a3.14.3-s4.14.8` works with recycle plugin

**Comment by MarvAmBass** [comment]
tested and available as `latest`

**Comment by MarvAmBass** [comment]
just tested the recycle plugin, it works now -> the last samba build on alpine seemed to have several major issues - it's a way better experience right now
