### ISSUE TITLE
Bump latest tag to samba 4.15.5, as 4.15.2 segfaults on our machine

### ISSUE THREAD

**Issue by DSTkrt** [ServerContainers/samba#57]
The samba version currently contained in servercontainers/samba:latest segfaults on our machine.
There is more recent version in apk (4.15.5) which fixes said issue, but this has not yet propagated into :latest.

**Comment by MarvAmBass** [comment]
newer build is running: will be pushed to `servercontainers/samba:a3.15.0-s4.15.5-r0` ~ 5 min

**Comment by MarvAmBass** [comment]
tested and available as `latest`
