### ISSUE TITLE
Server role 'member server' not supported?

### ISSUE THREAD

**Issue by gs4711** [ServerContainers/samba#64]
At least the configuration leads to duplicate server role statements within ````smb.conf````

Any ideas?

**Comment by MarvAmBass** [comment]
you can use `SAMBA_CONF_SERVER_ROLE` now to set the server role :)

please let me know if it works as expected :) thanks

**Comment by gs4711** [comment]
> please let me know if it works as expected :) thanks

Thanks, Marvin! It works as expected.
