### ISSUE TITLE
Guest user

### ISSUE THREAD

**Issue by noaho** [ServerContainers/samba#65]
Have you had any luck with guest login? No matter what I try, I seem to get NT_STATUS_ACCESS_DENIED

I did have success once mapping guest to the same UID as my share, but then it has rights I don't want it to have (eg write). 

And nobody user should still have read access to my share, the other permissions are r+x

Sorry if I haven't explained this clearly, I've been going crazy trying to get it to work.

**Comment by MarvAmBass** [comment]
I guess the user needs access permissions on the filesystem 

I have some similar setup where I made the guest share read only. If you're logged in you have write permissions.

https://askubuntu.com/questions/88108/samba-share-read-only-for-guests-read-write-for-authenticated-users
This describes it pretty well 😊

**Comment by noaho** [comment]
yeah.. The thing is all users have access to the share (read + execute)

For example I can run 
docker exec -it --user nobody samba sh

cd /shares/sharename
ls

and see all the files.. 

For your working setup, did you have to assign the guest user to a particular user, or did the defaults work?

**Comment by MarvAmBass** [comment]
My guest gets mapped to nobody.

I set my permissions on filesystem level accordingly 
So there are files and documents which wouldn't be accessible by nobody e.g guest.

If I want to share files or whole shares I overwrite permissions and force groups on the samba config level.

You can also use nobody and remove others from writing in the share 🤔
With chmod 775 for example

**Comment by noaho** [comment]
Thanks for your help! 

I found the problem, apparently I can't use valid user in combination with guest ok, unless I add the guest users (eg nobody) to valid user. 

EG, this works:
        - SAMBA_VOLUME_CONFIG_sharename=[sharename]; path=/shares/sharename; valid users = user1, user2, **nobody**; read only = yes; write list = user1; guest ok = yes; browseable = yes

**Comment by MarvAmBass** [comment]
good to know! have fun with the container :)
