### ISSUE TITLE
spotlight support

### ISSUE THREAD

**Issue by martijndierckx** [ServerContainers/samba#69]
Does this Docker container support the following?:

`SAMBA_VOLUME_CONFIG_public: "[Public]; path=/mnt/dataTank; browsable = yes; guest ok = yes; read only = yes; write list = share; spotlight backend = elasticsearch; elasticsearch:address = 192.168.10.100; elasticsearch:port = 9200;"
`

more specifically:
```
spotlight backend = elasticsearch
elasticsearch:address = 192.168.10.100
elasticsearch:port = 9200;
```

I'm getting the following error when starting the container, but I don't know yet if it has been triggered by the above:
```
tdb(/var/lib/samba/account_policy.tdb): tdb_open_ex: could not open file /var/lib/samba/account_policy.tdb: No such file or directory
Could not open tdb: No such file or directory
```

**Comment by MarvAmBass** [comment]
Hi Martijn, I'm pretty sure the spotlight backend should work - this tdb error ist has nothing to do with it.

worst case, spotlight support could not be part of the compilation of the alpine package, but I don't think they excluded it - just try if it works :)

**Comment by martijndierckx** [comment]
Just found the build log for samba on alpine.
Spotlight seems to be included, but not the ES backend for it... :-(

https://build.alpinelinux.org/buildlogs/build-3-16-x86_64/main/samba/samba-4.15.7-r0.log

**Comment by MarvAmBass** [comment]
strange, but it generates elasticsearch xml files... there is a debian port for this container in the pull requests, maybe you can fork my repo, merge this debian pull request and create your own debian flavored samba container

if you merge my upstream it should have all features as this alpine container

I was thinking about maintainig both as different versions, but maintaining a few containers in a stable manner is already a lot of work for a private project :)

but if you're lucky then the debian version should work :)

**Comment by martijndierckx** [comment]
I forked your code and set it up on ubuntu 22:04:
https://github.com/martijndierckx/samba-docker
