### ISSUE TITLE
Clients can see Samba server, but are unable to see/browse/connect to shares

### ISSUE THREAD

**Issue by Sal-Ammonite** [ServerContainers/samba#72]
**Host OS**: Debian Testing (Bookworm), current as at 28/12/22 06:00UTC
**Docker version**: Docker 20:10:21 (current stable version from https://download.docker.com/linux/debian/dists/bullseye/stable/ - there's no repository for Debian testing/Bookworm)
**Container version**: servercontainers/samba:smbd-avahi-latest (also occurs with samba:latest)
**Client OS**: Various - Debian testing/Bookworm, MacOS 12.6.1/12.6/12.5.1

**Issue**: Clients can see the server, but are unable to see shares, browse shares or connect to shares directly. Suspect this is related to a package update on Debian testing.

**Background**: Have been running this Samba container release happily for several months. A few weeks ago I updated the host OS to Debian Testing (Bookworm) to support other software (mailctl); everything had been running fine since then. In the last few days, something in recent Debian package updates seems to have resulted in a failure to browse/connect.

**Other Info**: I'm not 100% sure when this started - I first noticed share browsing had failed on 26/11/22. Initially thinking it was a firewall issue I completely cleared iptables and re-established default install settings with no change. After that, I completely uninstalled all docker containers & Docker, re-installed Docker from the above repository, and installed servercontainers/samba:smbd-avahi-latest from DockerHub.

**Testing**: Since it seemed avahi discovery was working fine, I modified my environment & increased the samba loglevel to 4. Examining the samba logs in the container showed initial startup seemed to be OK, but I noticed the following errors in /var/log/samba/log.rpcd_classic:

> [2022/11/28 04:42:56,  3] ../../source3/smbd/password.c:84(register_homes_share)
  Adding homes service for user 'redacteduser' using home directory: '/home/redacteduser'
[2022/11/28 04:42:56,  2] ../../lib/tdb_wrap/tdb_wrap.c:65(tdb_wrap_log)
  tdb(/var/lib/samba/share_info.tdb): **tdb_open_ex: could not open file /var/lib/samba/share_info.tdb: Permission denied**
[2022/11/28 04:42:56,  3] ../../lib/dbwrap/dbwrap_tdb.c:484(db_open_tdb)
  **Could not open tdb: Permission denied**
[2022/11/28 04:42:56,  0] ../../source3/lib/sharesec.c:161(share_info_db_init)
  Failed to open share info database /var/lib/samba/share_info.tdb (Permission denied)
[2022/11/28 04:42:56,  3] ../../libcli/security/dom_sid.c:216(dom_sid_parse_endp)
  **string_to_sid: SID redacteduser is not in a valid format**

Since this indicated a permissions issue with share_info.tdb, I looked at that:

> /var/log/samba # ls -al /var/lib/samba/share_info.tdb
-rw-------    1 root     root        421888 Nov 28 04:42 /var/lib/samba/share_info.tdb

Changing permissions from 600 to 660 didn't solve the problem, however changing them from 600 to 666 does - all clients could see the server, browse shares, read/write/create/delete files, etc as per normal. Reverting permissions back to the 'correct' 600 causes samba to once again fail.

Obviously opening up the permissions like that is not a good solution, security wise. Also, I can't fathom what changes *outside* the container may have caused this issue - but it seems that *something* has. Hopefully you might have an idea...

Thanks for looking, and I'm happy to attempt any further testing if needed.

**Comment by MarvAmBass** [comment]
Hi there,

thanks for this huge bug report, I rebuild my samba container about two days ago, can you check the tag from before?
tag should be `a3.16.2-s4.15.7-r0`

if this doesn't work, I'm not sure about the issue - maybe some major problem in bookworm?

maybe you could provide your `docker-compose` without secrets and personal stuff :)

**Comment by MarvAmBass** [comment]
I've still no updates on this ticket. what client / os has problems seeing those shares?

**Comment by Sal-Ammonite** [comment]
My apologies for the delay; have had a busy week & have been unable to check back / follow up.

The clients that were having issues were MacOS 12.6.1, 12.6, and 12.5.1 (all using mount_smbfs: version 4.0.0), and Debian testing/bookworm (smbclient 4.17.3). 

Noticed you'd just now updated 'latest' again (sha256:53abd2560f76d68586b40a173f1b2829580fd820dc64ac07cc9409a27d0a8781), so pulled & deployed it with a known-working minimal config. All clients are still unable to connect (as guests or valid users).

Looking back to my original report: obviously at some point when making a minor change I'd accidentally updated to the then-latest 'latest' without noticing (I'm using Portainer CE - so no docker compose as such - & "Always pull the image" defaults to "on", so it's too easy to do that). So, yeah, some change between a3.16.2-s4.15.7-r0 & later builds seems to be the root of the issue.

Thanks again for looking into it!

**Comment by MarvAmBass** [comment]
no problem, thanks for anwering the questions.

so connection is impossible for you? I don't have any problems with macos at all.
Maybe you need to connect directly via finder and samba url -> is this possible?

yeah I just rebuild the container and pushed it to latest, since I don't seem to have any issues.
And the group id/user id issue was obvious.


ahhh interessting, I don't know how this container behaves when it's run in a different container manager. maybe it failes to set up some stuff. does it have uid randomization activated on default? maybe some other security feature which is incompatible or needs to be explicitly enabled

**Comment by MarvAmBass** [comment]
note: if you don't have a avahi on your host, and run this container inside a private virtual network on your machine, zeroconf will not work -> that's why I always use network_mode: host on my samba, so avahi works on the correct network

**Comment by Sal-Ammonite** [comment]
Connection semi-works, as described below. The container is connected to the docker host network. I've also confirmed that there are no other avahi/mDNS/zeroconf or samba services running, or even installed, on the host.  The only avahi & samba services visible are those running in the container.

For testing, I created a "working" minimal config (single guest share) from scratch using the "a3.16.2-s4.15.7-r0" image, and confirmed it worked as expected. I then stopped that container, and duplicated it changing only "a3.16.2-s4.15.7-r0" to "latest".

In both cases, I can see the servers are announced by avahi, using avahi-browse on Linux (separate machine) and the "Discovery" utility (a Bonjour/mDNS/zeroconf DNS-SD browser app) on MacOS clients. I can also see the samba server in Linux on a separate machine using smbclient, and in MacOS through the Finder. However:
- With the the "a3.16.2-s4.15.7-r0" container I can see the share.
- With the "latest" container I can't see the share (though smbclient shows the root "$IPC" service). MacOS Finder reports a "connection failed" error.

So as far as it goes, everything seems to suggest that avahi in the container is working properly & visible to machines on the network in both cases, while samba works fully in the earlier image but only partially in the latest version.

I've attached docker logs from both working & non-working containers, created from scratch using fresh pulls of the images, covering from first startup to client connect / share browsing attempts. It seems Portainer does keep docker-compose.yaml files for containers it manages in its own container, but I'm yet to get them out (no shell in the Portainer container 🙄). I'll add them when I get them. Let me know if there's anything else you want to know/see that'll help.

[goodserver.log](https://github.com/ServerContainers/samba/files/10147619/goodserver.log)

[badserver.log](https://github.com/ServerContainers/samba/files/10147621/badserver.log)

**Comment by Tumist76** [comment]
I have the same issue. Can't access share from Mac. Avahi works fine, so I see the server in Finder, but it fails to connect. Direct Finder connect via `smb://`, not surprisingly, fails too.

Tried using  "a3.16.2-s4.15.7-r0" tag, but in my case, i couldn't see any difference.

My compose:
```yaml
samba:
  image: servercontainers/samba:a3.16.2-s4.15.7-r0
  container_name: samba
  restart: unless-stopped
  network_mode: host
  environment:
    MODEL: 'Macmini'
    AVAHI_NAME: RaspberryPi

    ACCOUNT_sambauser: test123
    UID_sambauser: 1000

    SAMBA_GLOBAL_STANZA: "load printers = no; printing = bsd; printcap name = /dev/null; disable spoolss = yes"
    SAMBA_VOLUME_CONFIG_shared_files: "[Files]; path=/shares/files_hdd/network_share; valid users = sambauser; guest ok = no; read only = no; browseable = yes"
    SAMBA_VOLUME_CONFIG_test: "[Test]; path=/home; guest ok = yes; read only = no; browseable = yes"
    SAMBA_CONF_LOG_LEVEL: 4

    WSDD2_DISABLE: true
  volumes:
    - /media/files_hdd:/shares/files_hdd
```

**Comment by MarvAmBass** [comment]
since it works with my setup fine

did you have any iptables rules which blocks the connection?

```
-A INPUT -p udp --dport 5353 -j ACCEPT -m comment --comment "avahi zeroconf"
-A INPUT -p tcp --dport 139 -j ACCEPT -m comment --comment "samba"
-A INPUT -p tcp --dport 445 -j ACCEPT -m comment --comment "samba"
```

those are the needed rules, maybe you can try to expose those ports explicitly without using `network_mode: host`
this way docker makes sure the ports are availe - but avahi will fail since it's limited to a docker internal network

if it works with the explicit way, you need to allow the ports mention in my iptables config

**Comment by MarvAmBass** [comment]
I also noticed, that there might be problems with ipv6 - if you use ipv6 internally, make sure the docker container opens ipv6 ports / or has a docker-proxy/ manual socat to convert ipv4 to ipv6

**Comment by Sal-Ammonite** [comment]
Just for info: I tested Dmitri's posted compose file here with only minor changes (deleted the "Files" share, & changed the container "Volumes" entry to suit my host's path), and it worked for me on a3.16.2-s4.15.7-r0. 

(Also, IPv6 is disabled on my host & there's no denying/blocking iptables rules - just the default rules installed by Docker.)

**Comment by MarvAmBass** [comment]
I'll close this - @Sal-Ammonite said it works, it works on my machine and serveral others - might be a docker-compose config error etc.

**Comment by JohanGroenenboom** [comment]
Just adding some more observations, hoping they might be helpful:  servercontainers/samba:latest also didn't work on my docker-compose setup on Ubuntu server 22.04 LTS host system. Going into the container, there is only a default /etc/samba/smb.conf, nothing that reflects the environment provided in the docker-compose.yml. Also, there is no /container folder. Going back to a3.16.2-s4.15.7-r0 everything works fine.

**Comment by MarvAmBass** [comment]
super strange, I updated today (a few hours ago) it still works without any problem on my nas.

I've just checked:

- `/container` ist available
- `smb.conf` is generated

maybe there are some problems with the selinux/apparmor config of ubuntu. did you try to mount any /etc/ folders into the container?

**Comment by JohanGroenenboom** [comment]
I have : 
``
volumes:
      - /etc/avahi/services/:/external/avahi
      - ...
``

**Comment by MarvAmBass** [comment]
does it work if you don't mount avahi and let the container start it's own avahi?

**Comment by JohanGroenenboom** [comment]
I tried running the latest samba container with the /external/avahi mapping removed. This didn't work either. Is this what you intended or should I do something more to "let the container start its own avahi" ?

**Comment by MarvAmBass** [comment]
super strange, it still works on my machines without an issue (different mac clients)

yeah it depends, on a server where you already have a few services running, for example avahi, there might be a port conflict. and if you mount you servers avahi config into the container avahi will work whether samba was able to start successfully.

what do your samba container logs say?

**Comment by MarvAmBass** [comment]
anyone experiencing this issues: maybe the infos here might help you too https://github.com/ServerContainers/samba/issues/79#issuecomment-1496693542

**Comment by Tumist76** [comment]
Following my previous comment from December 17: It works now!

I didn't change anything in config, firewall, OS or hardware, just temporarily dropped my plans on using this container. Now I've tried to change container tag to `smbd-avahi-a3.18.0-s4.18.2-r0` and it works perfectly! Don't know what @MarvAmBass changed in the latest versions, but thanks :)

**Comment by MarvAmBass** [comment]
that's good news! maybe some alpine package was broken and a rebuild fixed it. thanks
