### ISSUE TITLE
SAMBA_VOLUME_CONFIG_ should support colons

### ISSUE THREAD

**Issue by Tydus** [ServerContainers/samba#74]
Thanks for the great work! I especially like the idea of storing users' (hashed) passwords directly into the compose.yaml.

Currently, the space character in the global config key is specially handled, but sometimes we need colons(:) in the key as well.

FYI: `fruit:nfs_aces` needs to be in the section `[global]` in order to work.
https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html

Or, we can just support putting custom global config into one key, just like in `SAMBA_VOLUME_CONFIG_`.

**Comment by MarvAmBass** [comment]
thanks! I'll take a look! maybe I use some special escape sequence like `_COLON_` -> I already to something similar for spaces

**Comment by Tydus** [comment]
Wow that's fast!

Yeah, definitely `_COLON_` will do the trick. Waiting for your good news!
