### ISSUE TITLE
Why is there a volume created at '/shares'?

### ISSUE THREAD

**Issue by Cyberbeni** [ServerContainers/samba#75]
https://github.com/ServerContainers/samba/blob/20e36425068bbe1b661e0f7c74c030c31f26d183/Dockerfile#L24

It adds a volume with autogenerated name in docker. But if you only create shares for folders that you also mount then it will just contain empty folders that correlate with your mounts. (assuming your mounted them inside /shares)

**Comment by MarvAmBass** [comment]
thanks for the info. Unfortunately some environments (I know of openshift, but maybe only some hardened configurations) require this `VOLUME` definition in order to be able to mount any shares into a container.

In order to be versatilely usable this statement was added
