### ISSUE TITLE
FQDN for Avahi hostname

### ISSUE THREAD

**Issue by ko3n** [ServerContainers/samba#78]
When using a FQDN for an Avahi hostname it gets a .local extension.
Would it be possible to only set a FQDN for as Avahi hostname?

**Comment by MarvAmBass** [comment]
thanks for raising the issue - `.local` is the default domain extension for zeroconf (avahi is a zeroconf implementation)
https://en.wikipedia.org/wiki/Zero-configuration_networking#DNS-based_service_discovery

 but maybe there still is a bug and I need to transform a FQDN into a HOSTNAME


is there a way this issue is visible in reality? or is it just a strange/broken avahi config?
Note that `AVAHI_NAME` is supposed to be a hostname, not a FQDN

do you have an (maybe anonymized, reducted) example config and error message

**Comment by ko3n** [comment]
Understood regarding .local and zeroconf, I did indeed fill out a FQDN for AVAHI_NAME and this resulted in FQDN.local being broadcasted by avahi.

As I use FQDN inside the local network I am trying to get Avahi to broadcast the FQDN for time machine backups so that these backups will work from everywhere in my network.

Do you know of a way to get Avahi in your main docker image to broadcast an FQDN? I suppose this is an edge case, but for the sake of simplicity I rather not use an external Avahi server.

**Comment by MarvAmBass** [comment]
ahh I get what you want to do, and I also had this problem, but there is a nice way around this.

usually your mac displays your avahi server in finder, you can click on it, and configure it as timemachine backup storage - this will lead to the `.local` address which is being used.

but in some cases this doesn;t make sense - for example, multiple seperated networks (zeroconf only supports one network) or vpn access.
so even if your mac is able to connect to the server it doesn't know that it's the server which was previously configured using the zeroconf name.

the best way to work around this (I always to this on all my macs) use the finder and connect to server function. here you can use an IP or DNS name to connect to the server. Just establish the connection

now you openup timemachine and configure your timemachine to use the server you just configured. so the one with the FQDN or IP.
it should even detect if this server already contains a backup of you machine and continues using it.

after you configured it this way, timemachine will check if the machine is availbale and start it's backup process, even if you're connected to the server via vpn etc.


hope this helps :)

summary, I think you don't want zeroconf at all at your scenario - so make an explicit configuration for your network setup :)
zeroconf is simple and for everyday consumers without special needs regarding their networks :)

let me now if this helps, I should document this in my repo - might be helpful

**Comment by MarvAmBass** [comment]
added docu
