### ISSUE TITLE
Better error messages on malformed config

### ISSUE THREAD

**Issue by wmoss** [ServerContainers/samba#81]
I accidentally had a typo in a `SAMBA_VOLUME_CONFIG` and there was no error message, the container just started and then flapped trying to run `exec smbd --foreground`.

Example bad configuration line (missing `]` on the end of the name):
```
SAMBA_VOLUME_CONFIG_NAS: "[NAS; path=/shares/NAS/%U; valid users = wmoss, john; guest ok = no; read only = no; browseable = yes"
```

Container logs:
```
...
samba  | Enabled user wmoss.
samba  | >> VOLUME: adding volume: [NAS; path=/shares/NAS/%U; valid users = wmoss, john; guest ok = no; read only = no; browseable = yes (path=/shares/NAS/%U)
samba  |   >> multiuser volume - /shares/NAS/%U
samba  | >> ZEROCONF: samba.service file
samba  | ############################### START ####################################
samba  | <?xml version="1.0" standalone='no'?>
samba  | <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
samba  | <service-group>
samba  |  <name replace-wildcards="yes">%h</name>
samba  |  <service>
samba  |    <type>_smb._tcp</type>
samba  |    <port>445</port>
samba  |  </service>
samba  | </service-group>################################ END #####################################
samba  | >> WSDD2 - DISABLED
samba  | >> AVAHI - DISABLED
samba  | >> CMD: exec docker CMD
samba  | runsvdir -P /container/config/runit
samba  | + sleep 2
samba  | + exec smbd --foreground
samba  | + sleep 2
samba  | + exec smbd --foreground
samba  | + sleep 2
samba  | + exec smbd --foreground
...
```

**Comment by wmoss** [comment]
It didn't take me super long and it wasn't a production issue, it just required me to go back through the new config lines and reread them a bunch of times until I noticed the typo.

I assume `exec smbd --foreground` is producing some output about something being misconfigured that's not being printed into the logs? If so, even just showing those logs would help. I have `SAMBA_CONF_LOG_LEVEL` set to `3`.

The simplest solution might just be to add running `testparm -s` after you generate the config and print the output? If there's no problem it's a bit of noise in the logs and if there is a problem, it would show up clearly.

**Comment by MarvAmBass** [comment]
ohhh thanks for the hint `testparm -s` sounds like a nice solution for that!

**Comment by wmoss** [comment]
I've also been meaning to learn more about building docker containers, so if you don't get to this I'm happy to take a crack at it at some point.

**Comment by MarvAmBass** [comment]
Hey hey, I've just added this, and thanks for mentioning `testparm -s` it also gave me a hint to improve my default config ;)

**Comment by wmoss** [comment]
Awesome!
