### ISSUE TITLE
The fruit:advertise_fullsync is not exist in the samba official configuration document

### ISSUE THREAD

**Issue by aaftio** [ServerContainers/samba#86]
I can't find this config key in the official document, but find this [link](https://lists.samba.org/archive/samba/2020-January/227984.html) by google, it said:

> \# This isn't mentioned in the docs, hmm:
> \## INCORRECT PARAMETER - FULLSYNC ENABLE BY FRUIT:TIME MACHINE- SEE VFS_FRUIT DOC
> \##fruit:advertise_fullsync = true

So I want to know where this configuration is imported from. And thank you for your work on this wonderful project.

**Comment by MarvAmBass** [comment]
thanks for checking, the only thing I can guess is, that this was the correct flag a few years ago - this container is maintained for many years, and I always wanted to provide the timemachine support.

`fruit:time machine` seems to be the correct parameter

```
fruit:time machine = [ yes | no ]
Controls if Time Machine support via the FULLSYNC volume capability is advertised to clients.

yes - Enables Time Machine support for this share. Also registers the share with mDNS in case Samba is built with mDNS support.

no (default) Disables advertising Time Machine support.
```

**Comment by MarvAmBass** [comment]
thanks for raising this issue - it's good to see that some people take a deep look into this container! and super interessting, that testparm doesn't care about this non existing parameter
