### ISSUE TITLE
testparm check ignores SAMBA_GLOBAL_CONFIG_ with spaces

### ISSUE THREAD

**Issue by 2K-ZONE** [ServerContainers/samba#90]
...properly? Is it me?

In my docker-compose.yml I have:

      environment:

      XXX

      SAMBA_GLOBAL_CONFIG_server_SPACE_multi_SPACE_channel_SPACE_support: yes
      SAMBA_GLOBAL_CONFIG_aio_SPACE_read_SPACE_size: 1
      SAMBA_GLOBAL_CONFIG_aio_SPACE_write_SPACE_size: 1

      YYY

On Start with docker logs i get:

   \>\> global config - adding: 'aio read size' = '1' to /etc/samba/smb.conf
   \>\> global config - adding: 'server multi channel support' = 'yes' to /etc/samba/smb.conf
   \>\> global config - adding: 'aio write size' = '1' to /etc/samba/smb.conf

But the logs also show then the key/values are NOT added:

 [global]
	dns proxy = No
	load printers = No
	log file = /dev/stdout
	map to guest = Bad User
	obey pam restrictions = Yes
	passdb backend = smbpasswd
	printcap name = /dev/null
	security = USER
	server role = standalone server
	server string = Samba docker container on FALLEN
	smb1 unix extensions = No
	fruit:aapl = yes
	fruit:model = RackMac
	idmap config * : backend = tdb
	acl allow execute always = Yes
	wide links = Yes

Also when I manually check the smb.conf in container or run testparm, the values are not there.

**Comment by MarvAmBass** [comment]
I'll check moment :)

**Comment by MarvAmBass** [comment]
I've just tested your values - it's correct that testparm seems to ignore them, so they are not visible in the logs

but if you take a look at your samba config inside the container `cat /etc/samba/smb.conf | grep aio` those values are set

**Comment by 2K-ZONE** [comment]
Thank you very much. It is totally harmless testparm is ignoring those settings, I can agree to that.
Also I now learned the the logs put out testparm's view, not the real smb.conf file. Which has advantages and disadvantages - no problem -  but I was not aware.
What me bothers more is, that those parameters are indeed integrated into the global part of the /etc/samba/smb.conf successfully and correct. And I checked the fourth time and found them now finally.

So my initial statement "[...]I manually check the smb.conf in container[...]" was not wrong but I was to stupid to do it correctly.

Sorry and thanks for your support!

**Comment by MarvAmBass** [comment]
yeah I also don't understand why it's ignoring those - but maybe I can fix this in the future - maybe it really is an samba issue :D

sure no problem, maybe I should print the config on start into the logs

**Comment by MarvAmBass** [comment]
I'm going to close this issue, since it's just `testparm` which acts wierd - I don't maintain testparm in this repo - but the current config.

I've added a functionality to print the current `smb.conf` as well - so the differences between `testparm` and the whole config are transparent to the user/admin
