### ISSUE TITLE
How to expose shares with NodePort in Kubernetes

### ISSUE THREAD

**Issue by pablosettecase** [ServerContainers/samba#92]
I'm trying to expose Samba shares to outside of the cluster using a NodePort. I know this is not a good practice but it is something my team needs to accomplish. I can run a pod with two shares and it seems to work well, but I'm having trouble exposing them to the outside. Do you know if this is possible?

**Comment by MarvAmBass** [comment]
I'm not familiar with your described setup
But as long as port 445 is reachable you should be able to mount your stuff

It might be the case that port 139 is also needed - but from my understanding this is only some compatibility stuff which is not a hard requirement for modern clients 

If you're able to deploy and reach any other service in your kind of setup - samba shouldn't be different

**Comment by pablosettecase** [comment]
Update: After exposing the Samba server using NodePort you can connect to it by adding the "smb" to the scheme part of the URI like `smb\\myk8sclusterurl:<nodeport>\<sharename>`.
